### ISSUE TITLE
Issue when opening the Qlik Sense QVF File

### ISSUE THREAD

**Issue by dipankarqlik** [danielpilla/qlik-python-sse-google-translation#2]
Hi Daniel,

I was trying to leverage this translator. I have set-up everything as directed, and I run the __main__.py file. I then open Qlik Sense and see that the Translate & TranslateScript functions capabilities are called. However when I open the 1st sheet(Real time), it gives me the below error:

ERROR - Exception iterating responses: local variable 'translations' referenced before assignment
Traceback (most recent call last):
  File "C:\Users\DipankarM\Envs\QlikSenseAAI\lib\site-packages\grpc\_server.py", line 409, in _take_response_from_response_iterator
    return next(response_iterator), True
  File "__main__.py", line 107, in _translate
    resultList = [i.text for i in translations]
UnboundLocalError: local variable 'translations' referenced before assignment

Any pointers?

Also, the 2nd sheet(Raw Input), one extension object isn't available. I have downloaded the one qsvariable you mentioned, but seems like only dropdown is there and the Input box SR is invalid. Is that a different extension?

**Comment by dipankarqlik** [comment]
Hi Daniel,

Can you suggest something about this?
